table MM
	lineageTag: 53e96980-7b97-42a0-a3cd-a0492afe51c9

	column KEY
		dataType: string
		lineageTag: d6cc1e54-5462-40cd-822f-802838c8c103
		summarizeBy: none
		sourceColumn: KEY

		annotation SummarizationSetBy = Automatic

	column VOUCHERDATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9068941b-aa9a-4437-9bba-d3b0f7066608
		summarizeBy: none
		sourceColumn: VOUCHERDATE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ORDER_PRODUCT_ID
		dataType: string
		lineageTag: b2762de6-a313-41b3-87d9-709838e69db0
		summarizeBy: none
		sourceColumn: ORDER_PRODUCT_ID

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: double
		lineageTag: f30d20ba-4984-47d1-9ee5-8d5cdb2f3c86
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SELLINGPRICE
		dataType: double
		lineageTag: 7c9c8117-0f55-4391-ab88-1c31c5d64b3e
		summarizeBy: sum
		sourceColumn: SELLINGPRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LINE_TOTAL
		dataType: double
		lineageTag: c2aaf65e-96c4-4347-a86c-c852fe031f9b
		summarizeBy: sum
		sourceColumn: LINE_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LINE_DISCOUNT
		dataType: double
		lineageTag: ad75bee2-64f0-4db5-82be-28da1c633e32
		summarizeBy: sum
		sourceColumn: LINE_DISCOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LINE_STATUS
		dataType: double
		lineageTag: ea70210d-cb56-48c2-8ff6-2ebcc7e4ce20
		summarizeBy: sum
		sourceColumn: LINE_STATUS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LINE_TYPE
		dataType: string
		lineageTag: ee03f6fc-37cd-4c0e-9942-7aac07368771
		summarizeBy: none
		sourceColumn: LINE_TYPE

		annotation SummarizationSetBy = Automatic

	column MAIN_PRODUCT_NAME
		dataType: string
		lineageTag: 524aea9c-0466-4d00-a301-23f9b2840013
		summarizeBy: none
		sourceColumn: MAIN_PRODUCT_NAME

		annotation SummarizationSetBy = Automatic

	column REFERENCE
		dataType: string
		lineageTag: 833f3968-a462-484d-86f4-88902777d4e5
		summarizeBy: none
		sourceColumn: REFERENCE

		annotation SummarizationSetBy = Automatic

	column CATEGORY_ID
		dataType: string
		lineageTag: 2b5fe9ee-2505-4969-b3a1-d8fb6c0e6cad
		summarizeBy: none
		sourceColumn: CATEGORY_ID

		annotation SummarizationSetBy = Automatic

	column CategoryDescription
		dataType: string
		lineageTag: 6e75cb24-7a6e-44a7-99af-f1e7855d66e3
		summarizeBy: none
		sourceColumn: CategoryDescription

		annotation SummarizationSetBy = Automatic

	column CATEGORY_CREATED_AT
		dataType: string
		lineageTag: 3df0085c-b03f-42f7-a466-eca173b4e298
		summarizeBy: none
		sourceColumn: CATEGORY_CREATED_AT

		annotation SummarizationSetBy = Automatic

	column CATEGORY_UPDATED_AT
		dataType: string
		lineageTag: 1c5271ed-4510-425c-8efd-b0660262461f
		summarizeBy: none
		sourceColumn: CATEGORY_UPDATED_AT

		annotation SummarizationSetBy = Automatic

	column CATEGORY_DELETED_AT
		dataType: string
		lineageTag: 0468789e-4ef7-4fb8-ab1d-64b6daad8016
		summarizeBy: none
		sourceColumn: CATEGORY_DELETED_AT

		annotation SummarizationSetBy = Automatic

	column OPTION_PARENT_CATEGORY_NAME
		dataType: string
		lineageTag: 4011be9b-7872-4823-a856-e707978437ac
		summarizeBy: none
		sourceColumn: OPTION_PARENT_CATEGORY_NAME

		annotation SummarizationSetBy = Automatic

	column ProductName_Fixed_Option =
			
			
			VAR _brand = 'MM'[CHAINID]
			
			-- ══════════════════════════════════════════════
			-- TBL BRANCH
			-- ══════════════════════════════════════════════
			VAR _tbl =
			    IF(
			        'MM'[LINE_TYPE] = "OPTION"
			            && (
			                'MM'[SELLINGPRICE] > 0
			                || 'MM'[MAIN_PRODUCT_NAME] IN {
			                    "(Half)Deboned Chicken", "Deboned Chicken (Half)",
			                    "(Whole)Deboned Chicken", "Deboned Chicken (Whole)"
			                }
			            ),
			
			        IF(
			            'MM'[MAIN_PRODUCT_NAME] = "Create your own bowl"
			                || 'MM'[MAIN_PRODUCT_NAME] = "Deboned Chicken Rice Bowl",
			            'MM'[ItemDescription],
			
			            IF(
			                'MM'[ItemDescription] IN {
			                    "Regular", "Spicy", "Large", "Plain", "Plain Large",
			                    "Spicy Tabel™ Sauce", "Spicy Tabel™ Sauce Large",
			                    "Tabel™ Sauce", "Tabel™ Sauce Large",
			                    "SPICY", "REGULAR",
			                    "Coconut Curry Sauce",
			                    "Khishkhash", "Khishkhas",
			                    "Mushroom", "Spicy Tahini", "Tahini",
			                    "Without Sauce", "TAHINI", "SPICY TAHINI"
			                },
			                TRIM('MM'[MAIN_PRODUCT_NAME] & " " & 'MM'[ItemDescription]),
			
			                IF(
			                    'MM'[ItemDescription] IN {
			                        "Herb Tawouk", "Kabab", "Tawouk",
			                        "Tikka", "Shish Tawouk", "Herbs Tawouk"
			                    },
			                    TRIM('MM'[MAIN_PRODUCT_NAME] & " with " & 'MM'[ItemDescription]),
			                    'MM'[ItemDescription]
			                )
			            )
			        ),
			
			        'MM'[ItemDescription]
			    )
			
			-- ══════════════════════════════════════════════
			-- PAT BRANCH
			-- ══════════════════════════════════════════════
			VAR _pat =
			    IF(
			        'MM'[LINE_TYPE] = "OPTION"
			            && 'MM'[SELLINGPRICE] > 0
			            && 'MM'[ItemDescription] IN {"PLUS+", "Original"},
			        'MM'[MAIN_PRODUCT_NAME] & " " & 'MM'[ItemDescription],
			        'MM'[ItemDescription]
			    )
			
			-- ══════════════════════════════════════════════
			-- SS BRANCH
			-- ══════════════════════════════════════════════
			VAR _ss_CleanMain_Mix =
			    TRIM(
			        SUBSTITUTE(
			            SUBSTITUTE( 'MM'[MAIN_PRODUCT_NAME], "12pc", "" ),
			            "12 pc", ""
			        )
			    )
			
			VAR _ss_CleanDesc =
			    TRIM(
			        SUBSTITUTE(
			            SUBSTITUTE( LOWER('MM'[ItemDescription]), "12pc", "" ),
			            "12 pc", ""
			        )
			    )
			
			VAR _ss_CleanMain_Pieces =
			    TRIM(
			        SUBSTITUTE(
			            SUBSTITUTE( 'MM'[MAIN_PRODUCT_NAME], "(6 Pieces)", "" ),
			            "(4 Pieces)", ""
			        )
			    )
			
			VAR _ss_IsMix =
			    'MM'[ItemDescription] IN {
			        "Mix 4pc Regular & 8pc Spicy",
			        "Mix 8pc Regular & 4pc Spicy"
			    }
			
			VAR _ss_Is12pc =
			    LOWER('MM'[ItemDescription]) IN {
			        "12pc regular", "12 pc regular",
			        "12pc spicy",   "12 pc spicy"
			    }
			
			VAR _ss_IsPieces =
			    'MM'[ItemDescription] IN {
			        "6 Pieces Spicy", "6 Pieces Regular",
			        "4 Pieces Spicy", "4 Pieces Regular"
			    }
			
			VAR _ss_Resolved =
			    IF( _ss_IsMix,    _ss_CleanMain_Mix & " " & 'MM'[ItemDescription],
			    IF( _ss_Is12pc,   'MM'[MAIN_PRODUCT_NAME] & " " & _ss_CleanDesc,
			    IF( _ss_IsPieces, 'MM'[ItemDescription] & " " & _ss_CleanMain_Pieces,
			        'MM'[ItemDescription]
			    )))
			
			VAR _ss =
			    IF(
			        'MM'[LINE_TYPE] = "OPTION" && 'MM'[SELLINGPRICE] > 0,
			        _ss_Resolved,
			        _ss_Resolved
			    )
			
			-- ══════════════════════════════════════════════
			-- MSH BRANCH (replace MSH with actual CHAINID)
			-- ══════════════════════════════════════════════
			VAR _msh =
			    IF(
			        'MM'[LINE_TYPE] = "OPTION"
			            && 'MM'[SELLINGPRICE] > 0
			            && 'MM'[ItemDescription] IN {
			                "Regular","Healthy","XLarge",
			                "Spicy",
			                "Healthy Regular",
			                "Healthy Spicy",
			                "Saj",
			                "Lebanese Bread",
			                "Half & Half",
			                "Spicy Beef",
			                "Spicy Chicken",
			                "Spicy Half & Half",
			                "10 Chicken Shawarma Lebanese",
			                "10 Beef Shawerma Lebanese",
			                "10 Beef Shawarma Lebanese",
			                "16 Half Beef Philly Steak",
			                "16 Half Chicken Philly Steak",
			                "Kabab Wraps",
			                "Tawouk Wraps","Tawouk only","Kabab only","Mix",
			                "Plain (Vegetarian) Burghul",
			                "Plain (Vegetarian) Lettuce",
			                "With Grilled Chicken",
			                "With Tenderloin Steak"
			            },
			        'MM'[MAIN_PRODUCT_NAME] & " " & 'MM'[ItemDescription],
			        'MM'[ItemDescription]
			    )
			
			-- ══════════════════════════════════════════════
			-- ROUTE BY BRAND
			-- ══════════════════════════════════════════════
			RETURN
			    SWITCH(
			        _brand,
			        "TBL", _tbl,
			        "PAT", _pat,
			        "SS",  _ss,
			        "MM", _msh,   -- REPLACE MSH WITH ACTUAL CHAINID
			        'MM'[ItemDescription]
			    )
		lineageTag: 0f252791-bade-4fb9-9a48-4cda997c9826
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Clean_ItemID =
			
			VAR txt = LOWER('MM'[ItemID])
			
			RETURN
			IF(
			    ISBLANK(txt),
			    BLANK(),
			    CONCATENATEX(
			        FILTER(
			            GENERATESERIES(1, LEN(txt)),
			            MID(txt, [Value], 1) >= "0"
			                && MID(txt, [Value], 1) <= "9"
			        ),
			        MID(txt, [Value], 1),
			        ""
			    )
			)
		lineageTag: 1264be8c-54a5-4592-a42e-415671a9785c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CleanLocationID =
			
			SUBSTITUTE(
			SUBSTITUTE(
			SUBSTITUTE(
			SUBSTITUTE(
			SUBSTITUTE(
			    'MM'[LOCATIONID],
			    "JAH", "JHR"),
			    "TMHB", "MHB"),
			    "HAW", "HWL"),
			    "QAD", "QDS"),
			    "SBH", "SBS")
		lineageTag: 2bbb7bfc-e3e0-479c-bbeb-7598555a4ce6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OPTION_PARENT_PRODUCT_ID
		dataType: string
		lineageTag: e5da22e5-b7a6-4cb8-9755-8611215479aa
		summarizeBy: none
		sourceColumn: OPTION_PARENT_PRODUCT_ID

		annotation SummarizationSetBy = Automatic

	column PRODUCT_ID
		dataType: string
		lineageTag: 6fe60b4b-7fa4-41d8-a0e9-39ca57f72fe7
		summarizeBy: none
		sourceColumn: PRODUCT_ID

		annotation SummarizationSetBy = Automatic

	column NewItemID =
			
			CALCULATE(
			    SELECTEDVALUE('ITEM TABLE'[SKU]),
			    FILTER(
			        'ITEM TABLE',
			        'ITEM TABLE'[ID] = 'MM'[PRODUCT_ID]
			    )
			)
		lineageTag: 7d1840c8-f6f0-4767-946a-c953ea5aaf51
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CleanNewItemID =
			
			VAR ItemText = 'MM'[NewItemID]
			RETURN
			IF(
			    ISBLANK(ItemText),
			    BLANK(),
			    CONCATENATEX(
			        FILTER(
			            ADDCOLUMNS(
			                GENERATESERIES(1, LEN(ItemText)),
			                "Char", MID(ItemText, [Value], 1)
			            ),
			            [Char] >= "0" && [Char] <= "9"
			        ),
			        [Char],
			        ""
			    )
			)
		lineageTag: b6f380a1-f4fa-4a88-83d7-0132504cccd7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NEW_ID_final =
			
			IF(
			    NOT(ISBLANK([PRODUCT_ID])),
			    FORMAT([PRODUCT_ID], "0"),
			    IF(
			        NOT(ISBLANK([OPTION_PARENT_PRODUCT_ID])),
			        FORMAT([OPTION_PARENT_PRODUCT_ID], "0"),
			        ""
			    )
			)
		lineageTag: 3ba2158e-264b-487b-9f97-a3c6056be780
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ADDED_AT
		dataType: dateTime
		formatString: General Date
		lineageTag: c57a954b-ec3e-4e54-a485-cedfe76259a0
		summarizeBy: none
		sourceColumn: ADDED_AT

		variation Variation
			isDefault
			relationship: b7f35264-5614-4817-ac8a-df66d643679c
			defaultHierarchy: LocalDateTable_ba3f32db-59ab-4b93-b521-dd40404cd859.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CLOSED_AT
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c183f02-3902-47bb-a8e2-15044c313e07
		summarizeBy: none
		sourceColumn: CLOSED_AT

		variation Variation
			isDefault
			relationship: 203cc08a-1300-48db-be78-b032b3006a6a
			defaultHierarchy: LocalDateTable_91a3fa1e-5db4-4d36-84f6-92dc24cfccc4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ItemID
		dataType: string
		lineageTag: 703d5ee1-e7a2-4b52-a4bf-aaf6ca4a3eca
		summarizeBy: none
		sourceColumn: ItemID

		annotation SummarizationSetBy = Automatic

	column PRODUCT_BASE_PRICE
		dataType: double
		lineageTag: ff5658ee-2ecb-4dbe-a46d-d5571d7d4771
		summarizeBy: sum
		sourceColumn: PRODUCT_BASE_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ItemDescription
		dataType: string
		lineageTag: 99d579bf-2bde-43a7-b0cb-0a26b31129d6
		summarizeBy: none
		sourceColumn: ItemDescription

		annotation SummarizationSetBy = Automatic

	column LOCATIONID
		dataType: string
		lineageTag: f1e90ab6-9113-49cd-b9f6-46047af9ea4b
		summarizeBy: none
		sourceColumn: LOCATIONID

		annotation SummarizationSetBy = Automatic

	column CHAINID
		dataType: string
		lineageTag: 051c1e43-4a49-431a-8704-7e70902b1cdb
		summarizeBy: none
		sourceColumn: CHAINID

		annotation SummarizationSetBy = Automatic

	column BRANCHID
		dataType: string
		lineageTag: ed070d7b-3959-4287-8e17-9a75e1fe31ed
		summarizeBy: none
		sourceColumn: BRANCHID

		annotation SummarizationSetBy = Automatic

	column NEW_ID
		dataType: string
		lineageTag: 4cc83d74-7bb6-40e6-bca2-3c5edc339842
		summarizeBy: none
		sourceColumn: NEW_ID

		annotation SummarizationSetBy = Automatic

	partition MM = m
		mode: import
		source = ```
				let
				    // Connect to Snowflake
				    Source = Snowflake.Databases("UMWIJEO-IF31569.snowflakecomputing.com", "AIRBYTE_WAREHOUSE"),
				    AIRBYTE_FOODICS_Database = Source{[Name="AIRBYTE_FOODICS",Kind="Database"]}[Data],
				    AIRBYTE_MSH_Schema = AIRBYTE_FOODICS_Database{[Name="AIRBYTE_MSH",Kind="Schema"]}[Data],
				    V_ORDER_PRODUCTS_COMBINED_View = AIRBYTE_MSH_Schema{[Name="V_ORDER_PRODUCTS_COMBINED",Kind="View"]}[Data],
				    // Convert all column names to uppercase
				    #"Uppercase Column Names" = Table.RenameColumns(
				        V_ORDER_PRODUCTS_COMBINED_View,
				        List.Zip({
				            Table.ColumnNames(V_ORDER_PRODUCTS_COMBINED_View),
				            List.Transform(Table.ColumnNames(V_ORDER_PRODUCTS_COMBINED_View), Text.Upper)
				        })
				    ),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Uppercase Column Names",{{"BUSINESS_DATE", type date}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each ([BUSINESS_DATE] <> null)),
				    #"Sorted Rows1" = Table.Sort(#"Filtered Rows1",{{"BUSINESS_DATE", Order.Descending}}),
				
				    // Remove unused
				    #"Removed Columns" = Table.RemoveColumns(#"Sorted Rows1",
				        {"DISPLAY_NAME","PRODUCT_DESCRIPTION_LOCALIZED","DELAY_IN_SECONDS","RETURNED_QUANTITY",
				         "KITCHEN_NOTES","IS_INGREDIENTS_WASTED","PRODUCT_IMAGE","LINE_UUID",
				         "PRODUCT_DESCRIPTION","PRODUCT_CALORIES","PRODUCT_COST","PRODUCT_ACTIVE"}),
				
				    // Completed only
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([ORDER_STATUS] = 4 or [ORDER_STATUS] = 5)),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"ORDER_STATUS"}),
				
				    #"Renamed Columns3" =
				        Table.RenameColumns(#"Removed Columns1",
				            {{"QUANTITY","Qty"},{"PRODUCT_SKU","ItemID"},{"UNIT_PRICE","SellingPrice"},
				             {"PRODUCT_NAME","ItemDescription"}}),
				
				    #"Renamed Columns2" = Table.RenameColumns(#"Renamed Columns3",
				            {{"ORDER_ID","KEY"}, {"BUSINESS_DATE","VOUCHERDATE"}}),
				    #"Removed Columns5" = Table.RemoveColumns(#"Renamed Columns2",{"PRODUCT_NAME_LOCALIZED"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns5", "Custom", each Text.Combine({Text.From([ItemID]), Text.From([MODIFIER_OPTION_SKU])}, "_")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"Custom"}, #"PRODUCTS (3)", {"SKU"}, "PRODUCTS", JoinKind.LeftOuter),
				    #"Expanded PRODUCTS" = Table.ExpandTableColumn(#"Merged Queries", "PRODUCTS", {"NAME"}, {"PRODUCTS.NAME"}),
				    #"Added Custom1" = Table.AddColumn(#"Expanded PRODUCTS", "NAME", each if [PRODUCTS.NAME] = null or [PRODUCTS.NAME] = "" 
				then [ItemDescription] 
				else [PRODUCTS.NAME]),
				    #"Removed Columns3" = Table.RemoveColumns(#"Added Custom1",{"PRODUCTS.NAME"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns3",{{"ItemDescription", "1"}, {"NAME", "ItemDescription"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"ItemDescription", type text}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type2",{"1", "ItemID", "MODIFIER_OPTION_SKU"}),
				    #"Renamed Columns6" = Table.RenameColumns(#"Removed Columns2",{{"Custom", "ItemID"}}),
				
				    // Cleanup
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns6","(","",Replacer.ReplaceText,{"ItemDescription"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",")","",Replacer.ReplaceText,{"ItemDescription"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value1"," Thin - Pan - NY","",Replacer.ReplaceText,{"ItemDescription"}),
				
				    #"Renamed Columns4" = Table.RenameColumns(#"Replaced Value3",{{"VOUCHERDATE","VoucherDate"}}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Renamed Columns4",{{"BRANCH_ID","LocationId"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns5"),
				
				    #"FINAL" = #"Removed Duplicates",
				    #"Filtered Rows2" = Table.SelectRows(FINAL, each true),
				    #"Replaced Value6" = Table.ReplaceValue(#"Filtered Rows2"," Classic","",Replacer.ReplaceText,{"ItemDescription"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value6",{{"CATEGORY_NAME", "CategoryDescription"}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns", {"LocationId"}, #"MM BRANCHES (2)", {"ID"}, "MM BRANCHES", JoinKind.LeftOuter),
				    #"Expanded MM BRANCHES" = Table.ExpandTableColumn(#"Merged Queries1", "MM BRANCHES", {"NAME"}, {"MM BRANCHES.NAME"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Expanded MM BRANCHES", "MM BRANCHES.NAME", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"MM BRANCHES.NAME.1", "MM BRANCHES.NAME.2"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"MM BRANCHES.NAME.1", type text}, {"MM BRANCHES.NAME.2", type text}}),
				    #"Renamed Columns7" = Table.RenameColumns(#"Changed Type3",{{"LocationId", "BRANCHID"}, {"MM BRANCHES.NAME.1", "LOCATIONID"}, {"MM BRANCHES.NAME.2", "CHAINID"}, {"VoucherDate", "VOUCHERDATE"}, {"SellingPrice", "SELLINGPRICE"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns7",{"KEY", "VOUCHERDATE", "Qty", "SELLINGPRICE", "LINE_TOTAL", "LINE_DISCOUNT", "LINE_STATUS", "ItemID", "ItemDescription", "LINE_TYPE", "MAIN_PRODUCT_NAME", "REFERENCE", "CATEGORY_ID", "CategoryDescription", "CATEGORY_CREATED_AT", "CATEGORY_UPDATED_AT", "CATEGORY_DELETED_AT", "OPTION_PARENT_CATEGORY_NAME", "LOCATIONID", "CHAINID", "BRANCHID"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Reordered Columns",{{"VOUCHERDATE", type datetime}}),
				    #"Appended Query" = Table.Combine({#"Changed Type4", TBL})
				in
				    #"Appended Query"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

