table dim_date
	lineageTag: 5bcf9c4b-2bd6-4402-a88c-16048d92477d

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4849971-ff8f-47bd-ab78-9ba504b46a2e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 78c74cdb-2a23-4f52-828c-fb81463bf0c6
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month No'
		dataType: int64
		formatString: 0
		lineageTag: aa413417-9996-4738-ae62-5a36c90d34d8
		summarizeBy: sum
		sourceColumn: Month No

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 7e901ac7-2a34-4559-8aae-14c6f6a8a350
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 9632de1d-72a5-4cf9-8d30-cd100051ca53
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 756e2f61-c872-4c72-812c-578f62725b15
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Week No' = WEEKNUM(dim_date[Date], 2)
		formatString: 0
		lineageTag: a0f494ab-4b2a-4583-a102-092c93ccb4b5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    POStartDates =
				        List.RemoveNulls(fact_po_period_lifecycle[PO Start Date]),
				
				    POEndDates =
				        List.RemoveNulls(fact_po_period_lifecycle[PO End Date]),
				
				    GRNDates =
				        List.RemoveNulls(fact_grn_allocated_detail[GRN Delivery Date]),
				
				    AllDates =
				        List.Combine({POStartDates, POEndDates, GRNDates}),
				
				    MinDate =
				        List.Min(AllDates),
				
				    MaxDate =
				        List.Max(AllDates),
				
				    Dates =
				        List.Dates(
				            MinDate,
				            Duration.Days(MaxDate - MinDate) + 1,
				            #duration(1, 0, 0, 0)
				        ),
				
				    DateTable =
				        Table.FromList(
				            Dates,
				            Splitter.SplitByNothing(),
				            {"Date"}
				        ),
				
				    ChangedType =
				        Table.TransformColumnTypes(
				            DateTable,
				            {{"Date", type date}}
				        ),
				
				    AddedYear =
				        Table.AddColumn(
				            ChangedType,
				            "Year",
				            each Date.Year([Date]),
				            Int64.Type
				        ),
				
				    AddedMonthNo =
				        Table.AddColumn(
				            AddedYear,
				            "Month No",
				            each Date.Month([Date]),
				            Int64.Type
				        ),
				
				    AddedMonthName =
				        Table.AddColumn(
				            AddedMonthNo,
				            "Month Name",
				            each Date.MonthName([Date]),
				            type text
				        ),
				
				    AddedYearMonth =
				        Table.AddColumn(
				            AddedMonthName,
				            "Year Month",
				            each Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"),
				            type text
				        ),
				
				    AddedDayName =
				        Table.AddColumn(
				            AddedYearMonth,
				            "Day Name",
				            each Date.DayOfWeekName([Date]),
				            type text
				        )
				in
				    AddedDayName

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

