table 'STD PKG'
	lineageTag: 51eba8c3-9dff-4fc4-a67e-fe4b6d1642be

	column 'Item Group'
		dataType: string
		lineageTag: d264ffec-8646-4ad6-850d-06a5bccb3506
		summarizeBy: none
		sourceColumn: Item Group

		annotation SummarizationSetBy = Automatic

	column 'Article No.'
		dataType: int64
		formatString: 0
		lineageTag: d155b07e-3439-4ff5-a17e-82163ca6d836
		summarizeBy: sum
		sourceColumn: Article No.

		annotation SummarizationSetBy = Automatic

	column Article
		dataType: string
		lineageTag: b3841bd9-7c68-480d-b3e7-10d6c260b5d5
		summarizeBy: none
		sourceColumn: Article

		annotation SummarizationSetBy = Automatic

	column 'ARTICLE TYPE'
		dataType: string
		lineageTag: d88f2e62-4919-41d5-a9d9-9f37ea8ef766
		summarizeBy: none
		sourceColumn: ARTICLE TYPE

		annotation SummarizationSetBy = Automatic

	column 'IS ACTIVE'
		dataType: string
		lineageTag: 56b63193-2eb2-4370-b876-ec8898672b7e
		summarizeBy: none
		sourceColumn: IS ACTIVE

		annotation SummarizationSetBy = Automatic

	column 'ST.PACKAING'
		dataType: string
		lineageTag: 03b751ac-2a01-409f-9d92-55c93f9c2f08
		summarizeBy: none
		sourceColumn: ST.PACKAING

		annotation SummarizationSetBy = Automatic

	column 'YIELD %'
		dataType: string
		lineageTag: f1ea3fa5-3f34-42f9-87c1-7f9d14032e4a
		summarizeBy: none
		sourceColumn: YIELD %

		annotation SummarizationSetBy = Automatic

	column 'STORAGE TYPE'
		dataType: string
		lineageTag: cae23e5c-f2ec-4e94-a7b4-54075b311a7f
		summarizeBy: none
		sourceColumn: STORAGE TYPE

		annotation SummarizationSetBy = Automatic

	column 'SAFETY STOCK'
		dataType: string
		lineageTag: ca2d052c-7ef4-41fa-9695-0c95fcf3519a
		summarizeBy: none
		sourceColumn: SAFETY STOCK

		annotation SummarizationSetBy = Automatic

	column FROM
		dataType: string
		lineageTag: fd9e3562-0d2b-4703-8a64-63739eb465b9
		summarizeBy: none
		sourceColumn: FROM

		annotation SummarizationSetBy = Automatic

	partition 'STD PKG' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://etckuwait-my.sharepoint.com/personal/farha_swishhh_net/Documents/Swish%20SPS%20V3%202026.xlsm"), null, true),
				    #"STD PKG_Sheet" = Source{[Item="STD PKG",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"STD PKG_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Item Group", type text}, {"Article No.", Int64.Type}, {"Article", type text}, {"ARTICLE TYPE", type text}, {"IS ACTIVE", type text}, {"ST.PACKAING", type text}, {"YIELD %", type text}, {"STORAGE TYPE", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

