table 'Store SOH'
	lineageTag: 156b95e7-0a40-47c3-b1e5-9cee8082a5bf

	column 'Cost Center/Store'
		dataType: string
		lineageTag: 6529303e-0993-43b4-b8d9-fc65163b27da
		summarizeBy: none
		sourceColumn: Cost Center/Store

		annotation SummarizationSetBy = Automatic

	column 'Article No.'
		dataType: int64
		formatString: 0
		lineageTag: 64156536-aa58-4a43-a478-052d003f6ec8
		summarizeBy: sum
		sourceColumn: Article No.

		annotation SummarizationSetBy = Automatic

	column Article
		dataType: string
		lineageTag: c1902146-a55a-4380-b526-63df2f4b3719
		summarizeBy: none
		sourceColumn: Article

		annotation SummarizationSetBy = Automatic

	column 'ACT SOH'
		dataType: double
		lineageTag: 5e826c3e-92cc-4215-8837-01c9abc2dbac
		summarizeBy: sum
		sourceColumn: ACT SOH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Base Unit'
		dataType: string
		lineageTag: 804229c3-4411-4fad-99b5-be88afb75c5f
		summarizeBy: none
		sourceColumn: Base Unit

		annotation SummarizationSetBy = Automatic

	column 'P. Price'
		dataType: double
		lineageTag: 9cae9a4c-804b-4196-af85-977bb7537436
		summarizeBy: sum
		sourceColumn: P. Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVE
		dataType: double
		lineageTag: 0d2b73fe-11c0-4957-b3e2-c8f13d482253
		summarizeBy: sum
		sourceColumn: AVE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total per AVE'
		dataType: double
		lineageTag: 0fd11515-af0d-4e7d-b631-928eceb47dd6
		summarizeBy: sum
		sourceColumn: Total per AVE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'S.Price'
		dataType: double
		lineageTag: d9fc7a61-a77c-4a57-afe2-bc665390a8f1
		summarizeBy: sum
		sourceColumn: S.Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total S.Price/BU'
		dataType: double
		lineageTag: 69c6393c-9489-435a-873c-4f03e14f8c21
		summarizeBy: sum
		sourceColumn: Total S.Price/BU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MIN SOH'
		dataType: double
		lineageTag: 62158825-8cd7-4d9e-bdf6-0285bb17866f
		summarizeBy: sum
		sourceColumn: MIN SOH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'POT SOH'
		dataType: double
		lineageTag: 580592c2-5725-4f16-9a69-b89111c64051
		summarizeBy: sum
		sourceColumn: POT SOH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Storage Location'
		dataType: string
		lineageTag: 03e835e2-5a03-40a8-bbb7-fb76e1aa15bc
		summarizeBy: none
		sourceColumn: Storage Location

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 9dfc15ac-b94b-4753-833a-55f6f3702003
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	partition 'Store SOH' = m
		mode: import
		source = ```
				let
				
				    // SQL statement sent directly to the Oracle database
				    SqlQuery = "
				SELECT
				    k.KST_NAME AS ""Cost Center/Store"",      
				    -- Cost Center / Store name from KOSTST table
				
				    a.art_nummer AS ""Article No."",          
				    -- MC article number
				
				    a.ART_NAME AS ""Article"",                
				    -- Article description/name
				
				    d.day_sohend AS ""ACT SOH"",              
				    -- Actual Stock On Hand for the selected DAILYTOTALS date
				
				    v.VPK_NAME AS ""Base Unit"",              
				    -- Article base unit
				
				    d.day_pricelast AS ""P. Price"",          
				    -- Last purchase price
				
				    d.day_price AS ""AVE"",                   
				    -- Average inventory/value price
				
				    d.day_sohend * d.day_price AS ""Total per AVE"",
				    -- Total stock value based on ACT SOH × Average Value
				
				    l.la_vkp AS ""S.Price"",                  
				    -- Selling price stored in LAGER
				
				    d.day_sohend * l.la_vkp AS ""Total S.Price/BU"",
				    -- Total stock value based on ACT SOH × Selling Price
				
				    l.la_mindestbestand AS ""MIN SOH"",       
				    -- Minimum stock level
				
				    l.la_sollbestand AS ""POT SOH"",          
				    -- Target / desired stock level
				
				    z.lgp_name AS ""Storage Location"",       
				    -- Physical storage location
				
				    v2.VPK_NAME AS ""Unit""                   
				    -- Secondary/article unit
				
				
				FROM
				
				    lager l
				    -- Main store/article inventory table
				
				    LEFT JOIN LAGERPLATZ z
				        ON l.LGP_nr = z.LGP_ID
				    -- Connects inventory record to Storage Location
				    -- LEFT JOIN means inventory can still appear even if Storage Location is missing
				
				    ,
				
				    artikel a,
				    -- Article master
				
				    vpckeinh v,
				    -- Base unit table
				
				    vpckeinh v2,
				    -- Secondary unit table
				
				    warengruppe w,
				    -- Article/commodity group
				
				    sparte s,
				    -- Division/category table
				
				    spartegr s1,
				    -- Division group table
				
				    kostst k,
				    -- Cost Center / Store master
				
				    dailytotals d
				    -- Daily stock snapshot/history table
				
				
				WHERE
				
				    a.art_id = l.art_nr
				    -- Connects LAGER inventory to Article master
				
				    AND v.vpk_id = a.vpk_nr
				    -- Connects article to its Base Unit
				
				    AND a.wgr_id = w.wgr_id
				    -- Connects Article to Article Group
				
				    AND w.spa_id = s.spa_id
				    -- Connects Article Group to Division
				
				    AND a.vpk_nr2 = v2.vpk_id
				    -- Connects Article to its secondary Unit
				
				    AND s.sgr_id = s1.sgr_id
				    -- Connects Division to Division Group
				
				    AND l.kst_id = k.kst_id
				    -- Connects LAGER inventory to Cost Center / Store
				
				
				    -- COST CENTER FILTER REMOVED
				    -- Previously:
				    -- AND k.kst_index LIKE 'AAAPAB%'
				    --
				    -- Because this condition is removed,
				    -- the query can now return ALL Cost Centers / Stores
				    -- available through the LAGER + KOSTST relationship.
				
				
				    AND a.art_notinv = 0
				    -- Keeps articles where ART_NOTINV = 0
				    -- This is the inventory-related article filter used by the original query
				
				    AND l.aktiv = ' '
				    -- Keeps LAGER records where AKTIV contains a blank space
				    -- Preserved exactly from the existing MC query
				
				    AND d.kst_id = l.kst_id
				    -- DAILYTOTALS Cost Center must match LAGER Cost Center
				
				    AND d.art_id = l.art_nr
				    -- DAILYTOTALS Article must match LAGER Article
				
				    AND d.day_date = TRUNC(SYSDATE)
				    -- Returns DAILYTOTALS records for TODAY only
				
				
				ORDER BY
				
				    k.kst_index,
				    -- Sort first by Cost Center index
				
				    a.ART_NAMEID
				    -- Second sorting field
				    -- Kept exactly as it appears in your current working MC query
				",
				
				
				    Source =
				        Oracle.Database(
				            "192.168.1.99/mc",
				            [
				                Query = SqlQuery,
				                CommandTimeout = #duration(0, 0, 30, 0)
				            ]
				        ),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([#"Cost Center/Store"] <> "Al MANSOUR WAREHOUSE (PNFDC)" and [#"Cost Center/Store"] <> "Defense Meal" and [#"Cost Center/Store"] <> "MAIN WAREHOUSE (FDC)" and [#"Cost Center/Store"] <> "Marketing" and [#"Cost Center/Store"] <> "Merchandise Warehouse" and [#"Cost Center/Store"] <> "shopify" and [#"Cost Center/Store"] <> "Shrimpy" and [#"Cost Center/Store"] <> "Warehouse  Common  Al Mansour" and [#"Cost Center/Store"] <> "Warehouse  ERMG-Mishmash" and [#"Cost Center/Store"] <> "Warehouse  Non Moving items" and [#"Cost Center/Store"] <> "Warehouse Ardiya" and [#"Cost Center/Store"] <> "Warehouse ETC Al Mansour" and [#"Cost Center/Store"] <> "Warehouse ETC Arwa" and [#"Cost Center/Store"] <> "Warehouse FM" and [#"Cost Center/Store"] <> "Warehouse Just C" and [#"Cost Center/Store"] <> "Warehouse Space (BBT)" and [#"Cost Center/Store"] <> "Warehouse Yelo Al Mansour" and [#"Cost Center/Store"] <> "Warehouse Yelo arwa"))
				in
				    #"Filtered Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

