/**
 * The schema, as PostgreSQL.
 *
 * One consolidated step rather than the sixteen incremental ones the SQLite
 * build accumulated. Replaying that history against a new engine would have
 * meant translating several table rebuilds whose only purpose was to widen a
 * CHECK constraint SQLite cannot alter — work that produces exactly the schema
 * written out here, with more ways to get it wrong.
 *
 * Later changes go on the end of this list as their own steps. Each runs once,
 * in order, inside a transaction, and is recorded.
 *
 * Two notes on the translation:
 *
 *   Timestamps stay TEXT in 'YYYY-MM-DD HH:MM:SS'. They could be timestamptz,
 *   but the application compares and slices them as strings in a dozen places
 *   and changing the storage type would have meant changing all of it for no
 *   behavioural gain.
 *
 *   Email uniqueness was COLLATE NOCASE, which PostgreSQL has no equivalent
 *   for. A unique index on lower(email) does the same job, and every lookup
 *   already goes through the same helper.
 */

const NOW = "to_char(now(), 'YYYY-MM-DD HH24:MI:SS')"

export const MIGRATIONS = [
  {
    name: '001_initial',
    sql: `
      CREATE TABLE users (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email           TEXT    NOT NULL,
        name            TEXT    NOT NULL DEFAULT '',
        password_hash   TEXT    NOT NULL,
        role            TEXT    NOT NULL CHECK (role IN ('admin','stakeholder','store','viewer')),
        status          TEXT    NOT NULL DEFAULT 'active'
                                CHECK (status IN ('pending','active','suspended','disabled')),
        failed_attempts INTEGER NOT NULL DEFAULT 0,
        locked_until    TEXT,
        created_at      TEXT    NOT NULL DEFAULT ${NOW},
        last_login_at   TEXT,
        department      TEXT,
        auth_provider   TEXT    NOT NULL DEFAULT 'local'
      );
      CREATE UNIQUE INDEX idx_users_email ON users (lower(email));

      -- One row per grant. NULL means "all" for that dimension, so a
      -- stakeholder owning three brands is three rows, not a schema change.
      CREATE TABLE user_scopes (
        id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        brand_code  TEXT,
        location_id TEXT
      );
      CREATE INDEX idx_user_scopes_user ON user_scopes(user_id);

      -- Only a hash of the session id is stored, so a database copy cannot be
      -- replayed as a live session.
      CREATE TABLE sessions (
        id           TEXT    PRIMARY KEY,
        user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at   TEXT    NOT NULL DEFAULT ${NOW},
        expires_at   TEXT    NOT NULL,
        last_seen_at TEXT    NOT NULL DEFAULT ${NOW},
        revoked_at   TEXT,
        ip           TEXT,
        user_agent   TEXT
      );
      CREATE INDEX idx_sessions_user ON sessions(user_id);

      CREATE TABLE login_events (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
        email_attempted TEXT    NOT NULL,
        success         INTEGER NOT NULL,
        reason          TEXT,
        ip              TEXT,
        user_agent      TEXT,
        created_at      TEXT    NOT NULL DEFAULT ${NOW}
      );
      CREATE INDEX idx_login_events_user ON login_events(user_id);
      CREATE INDEX idx_login_events_created ON login_events(created_at);

      CREATE TABLE audit_log (
        id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
        action        TEXT    NOT NULL,
        target        TEXT,
        detail_json   TEXT,
        created_at    TEXT    NOT NULL DEFAULT ${NOW}
      );
      CREATE INDEX idx_audit_created ON audit_log(created_at);

      CREATE TABLE digests (
        day          TEXT PRIMARY KEY,
        generated_at TEXT NOT NULL,
        reason       TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        acked_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
        acked_at     TEXT
      );

      CREATE TABLE alerts (
        id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source        TEXT    NOT NULL,
        key           TEXT    NOT NULL,
        severity      TEXT    NOT NULL DEFAULT 'warning',
        title         TEXT    NOT NULL,
        detail        TEXT,
        count         INTEGER NOT NULL DEFAULT 1,
        first_seen_at TEXT    NOT NULL DEFAULT ${NOW},
        last_seen_at  TEXT    NOT NULL DEFAULT ${NOW},
        resolved_at   TEXT,
        resolved_by   INTEGER REFERENCES users(id) ON DELETE SET NULL
      );
      -- One open alert per key; resolved ones may repeat.
      CREATE UNIQUE INDEX idx_alerts_open_key ON alerts(key) WHERE resolved_at IS NULL;
      CREATE INDEX idx_alerts_last_seen ON alerts(last_seen_at);

      CREATE TABLE email_log (
        id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        day        TEXT    NOT NULL,
        user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
        email      TEXT    NOT NULL,
        role       TEXT    NOT NULL,
        subject    TEXT,
        status     TEXT    NOT NULL CHECK (status IN ('sent','failed','skipped')),
        error      TEXT,
        meta_json  TEXT,
        created_at TEXT    NOT NULL DEFAULT ${NOW}
      );
      CREATE INDEX idx_email_log_day ON email_log(day);
      CREATE INDEX idx_email_log_created ON email_log(created_at);

      -- 'branch_forecast' is in this list where the SQLite build's was never
      -- widened for it: adding a recipient of that kind would have been
      -- rejected by the constraint.
      CREATE TABLE email_recipients (
        id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email      TEXT    NOT NULL,
        name       TEXT,
        report     TEXT    NOT NULL
                   CHECK (report IN ('store_plan','branch_forecast','brand_summary','daily_digest')),
        brands     TEXT,
        locations  TEXT,
        active     INTEGER NOT NULL DEFAULT 1,
        user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
        created_at TEXT    NOT NULL DEFAULT ${NOW},
        created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
        department TEXT
      );
      CREATE UNIQUE INDEX idx_recipient_email_report ON email_recipients(email, report);

      -- The one mailbox the app may send as. One row, ever. The refresh token
      -- is stored encrypted; see mail/delegated.js.
      CREATE TABLE mail_identity (
        id            INTEGER PRIMARY KEY CHECK (id = 1),
        email         TEXT NOT NULL,
        refresh_token TEXT NOT NULL,
        connected_at  TEXT NOT NULL DEFAULT ${NOW},
        connected_by  INTEGER
      );

      -- The local copy of the forecast, at the grain the Overview reads it.
      -- Article grain lives in its own table without the branch column; with
      -- it that is four hundred thousand rows per brand per sixty days, past
      -- what the Power BI query API will return in one go.
      CREATE TABLE cube_daily (
        brand    TEXT NOT NULL,
        date     TEXT NOT NULL,
        location TEXT NOT NULL,
        product  TEXT NOT NULL,
        actual   DOUBLE PRECISION NOT NULL DEFAULT 0,
        forecast DOUBLE PRECISION NOT NULL DEFAULT 0,
        PRIMARY KEY (brand, date, location, product)
      );
      CREATE INDEX idx_cube_brand_date ON cube_daily(brand, date);
      CREATE INDEX idx_cube_loc_cover ON cube_daily(brand, location, date, actual, forecast);

      CREATE TABLE cube_product_daily (
        brand    TEXT NOT NULL,
        date     TEXT NOT NULL,
        product  TEXT NOT NULL,
        actual   DOUBLE PRECISION NOT NULL DEFAULT 0,
        forecast DOUBLE PRECISION NOT NULL DEFAULT 0,
        PRIMARY KEY (brand, date, product)
      );

      CREATE TABLE cube_article_daily (
        brand    TEXT NOT NULL,
        date     TEXT NOT NULL,
        article  TEXT NOT NULL,
        product  TEXT NOT NULL,
        actual   DOUBLE PRECISION NOT NULL DEFAULT 0,
        forecast DOUBLE PRECISION NOT NULL DEFAULT 0,
        PRIMARY KEY (brand, date, article, product)
      );

      CREATE TABLE cube_coverage (
        brand        TEXT PRIMARY KEY,
        from_date    TEXT NOT NULL,
        to_date      TEXT NOT NULL,
        rows         INTEGER NOT NULL DEFAULT 0,
        refreshed_at TEXT NOT NULL DEFAULT ${NOW}
      );
    `,
  },
]
